name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: ${{ env.dist }}
        setup:
          run: pnpm run build:js
          cwd: ./ember-aria-utilities
        expect: |
          _app_/modifiers/aria-grid.js
          modifiers/aria-grid.d.ts
          modifiers/aria-grid.js
          modifiers/aria-grid.js.map
          test-support/index.js
          test-support/index.js.map
          test-support/index.d.ts
          
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
